name: burulas
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.3
  location: ^4.4.0
  multi_select_flutter: ^4.1.3
  http: ^0.13.5
  flutter_expandable_fab: ^1.6.1
  url_launcher: ^6.1.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/